###############################################################################
# Example invocation:
# ansible-playbook cluster-create.yml -e "cluster_name=foo master_ip_address=<ip> admission_token=<token>"
#
###############################################################################
# Required args:
# cluster_name
# master_ip_address
# admission_token
###############################
---

# Installing kubelet and kubeadm on your hosts
# Step (1/4) http://kubernetes.io/docs/getting-started-guides/kubeadm/

- hosts: "{{ cluster_name }}"
  become: true
  roles:
    - role: common
      tags:
        - repo
        - master
        - nodes

# Initialize master
# Step (2/4) and (3/4) http://kubernetes.io/docs/getting-started-guides/kubeadm/

- hosts: "{{ cluster_name }}_master"
  become: true
  roles:
    - role: master
      tags:
        - master
        - init

# Joining nodes
# Step (4/4) http://kubernetes.io/docs/getting-started-guides/kubeadm/
        
- hosts: "{{ cluster_name }}_node"
  become: true
  roles:
    - role: nodes
      tags:
        - nodes
        - join


