---
# tasks file for individual nodes

# Joining nodes
# Step (4/4) http://kubernetes.io/docs/getting-started-guides/kubeadm/

- debug:
    var: admission_token
  run_once: true

- debug:
    var: master_ip_address
  run_once: true

- name: Join nodes to cluster
  command: kubeadm join --token {{ admission_token }} {{ master_ip_address }}:6443
  args:
    creates: /etc/kubernetes/kubelet.conf
  register: node_join
  ignore_errors: true

- debug:
    var: node_join.stdout_lines

