---
# tasks file for master node init

# Implements Step 3 of http://kubernetes.io/docs/getting-started-guides/kubeadm/
# (3/4) Installing a pod network

- name: Install pod network
  shell: "curl -sSL {{ item }} | kubectl --kubeconfig /etc/kubernetes/admin.conf create -f -"
  register: pod_network
  with_items: "{{ networking_addons }}"
  tags:
    - master
    - network

- debug:
    var: pod_network.stdout_lines 

- name: Wait for Kube-DNS pod running
  shell: "kubectl --kubeconfig /etc/kubernetes/admin.conf get pods --all-namespaces | grep kube-dns"
  register: result
  until: result.stdout.find("Running") != -1
  retries: 30
  delay: 10        
